"""migracion_inicial

Revision ID: 8acedd05a0d4
Revises: 
Create Date: 2026-04-21 17:18:33.729567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8acedd05a0d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('registros_destinatarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sede', sa.Enum('AJUSCO', 'COYOACAN', name='sede_enum'), nullable=False),
    sa.Column('nombre_imagen', sa.String(length=255), nullable=False),
    sa.Column('destinatario_raw', sa.Text(), nullable=False),
    sa.Column('nombre_o_titulo', sa.String(length=255), nullable=True),
    sa.Column('cargo_dependencia', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('colonia', sa.String(length=255), nullable=True),
    sa.Column('municipio_o_alcaldia', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), nullable=True),
    sa.Column('codigo_postal', sa.String(length=6), nullable=True),
    sa.Column('extras', sa.Text(), nullable=True),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('indicaciones', sa.Text(), nullable=True),
    sa.Column('observaciones_ia', sa.Text(), nullable=True),
    sa.Column('crop_x', sa.Integer(), nullable=True),
    sa.Column('crop_y', sa.Integer(), nullable=True),
    sa.Column('crop_w', sa.Integer(), nullable=True),
    sa.Column('crop_h', sa.Integer(), nullable=True),
    sa.Column('rotation_deg', sa.Integer(), nullable=True),
    sa.Column('aspect_mode', sa.Enum('FREE', 'SQUARE', name='aspect_mode_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_destinatarios_id'), 'registros_destinatarios', ['id'], unique=False)
    op.create_index(op.f('ix_registros_destinatarios_sede'), 'registros_destinatarios', ['sede'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_destinatarios_sede'), table_name='registros_destinatarios')
    op.drop_index(op.f('ix_registros_destinatarios_id'), table_name='registros_destinatarios')
    op.drop_table('registros_destinatarios')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
